### ISSUE TITLE
Needs ASMDEF files for use in modern Unity

### ISSUE THREAD

**Issue by gekidoslair** [heathen-engineering/Heathen-System-Core#1]
Any modern code framework in Unity needs to use ASMDef files so that they can be properly managed in the codebase. 

https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html

**Comment by JamesMcGhee** [comment]
1st not every tool kit can work that way due to how Unity handles plug-in references so for example Steamworks.NET has issues when you build extension on it that are wrapped up in assemblies that way, however this kit can work with them and does ... you will see we have defined HeathenEngineering.Core and HeathenEngineering.Core.Toolbox. The definitions are in the Framework folders under SystemsCore and Toolbox respectivly. 

Let us know if you find some issue with the current assembly set up

**Comment by gekidoslair** [comment]
My main goal is to move all of the code in this library into a package so that it isn't a part of my actual Unity project.  I would look at platforms like OpenUPM.com as ways to deliver your library via a package registry for example. 

Ideally developer should not have to manually bake your library into their Unity project in order to use them.  I don't see what having plugin references would do to prevent wrapping the project in assembly defines - should be perfectly doable, in fact this is how Unity itself wraps binary / platform libraries etc. 

Up to you of course, but would make the library much more accessible to developers this way.

**Comment by JamesMcGhee** [comment]
Thanks for the feedback
